# Default values for bender-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  # This is bad practice! In the real world, these secrets should be hidden somehow,
  # likely through a secret manager like Vault.
  ingress:
    host: vishaalk.cis188.org
    path: "/"
    secretName: "vishaalk-cis188-org-tls"

fastapi:
  image: ghcr.io/vishaalpkumar/cis188-final/final-project-backend-public
  tag: v2
  events_url: https://api.github.com/repos/VishaalPKumar/CIS188-Final/contents/data/events.yaml
  committer_name: "Vishaal Kumar"
  committer_email: "vishaalk@seas.upenn.edu"

react:
  image: ghcr.io/vishaalpkumar/cis188-final/final-project-frontend-public
  tag: v2
