apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: "calendar.cis188.org"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 8000
  tls:
    - hosts:
        - "calendar.cis188.org"
      secretName: calendar-cis188-org-tls
