kind: Service
apiVersion: v1
metadata:
  name: web-app
spec:
  selector:
    app: web-app
  ports:
    - port: 3000
      targetPort: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: ghcr.io/dlike230/cis188-project/final-project-frontend-public:${TAG}
          ports:
            - containerPort: 3000
