kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-calendar
          image: frontend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      restartPolicy: Always
