kind: Service
apiVersion: v1
metadata:
  name: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-calendar
          image: ghcr.io/vishaalpkumar/cis188-project/final-project-frontend-public:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
