apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
  labels:
    app: {{ .Release.Name }}-fastapi
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-fastapi
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
  labels:
    app: {{ .Release.Name }}-fastapi
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
        - name: fastapibackend
          image: "{{ .Values.fastapi.image }}:{{ .Values.fastapi.tag }}"
          ports:
            - containerPort: 8000

